rate-limit:
  rules-cache-ttl-seconds: 60
  max-bucket-count: 500000

feature-flags:
  cache-ttl-seconds: 30

logging:
  level:
    ua.kpi.sc: WARN
    org.springframework: WARN

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
